# Generated by Django 2.2.7 on 2019-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hashtag_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
